appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32d1a7d1578b0700305ba3
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: iI+iicDhiLr5HrYtjuSUvdMeJDpUlbOM88HHkML5kPjy1+u2AyKSGjTNxIrWREhqULOCjqEThMyh+NlJTA5V5/5wG6lqPLGLMqIzARRdHIVm5EmOFsemc4sXyb28hBW73z1MbgtC+nK5kMRzm5UOyqIR5ACseo47H3J/zmr5Gtsi1ZwQgpzzy1UGVhVvA1RogKESvrnGw1vBNK+hqvdNFr/tQrGoXDHpqyy601LN47ufCLuwo83ciZseiRvKoWJHJleZCVRrn+uniQk6lzI/6B1At4paMSEEJ4NaicDJaS7Nseoljkid3/LH3GU6SGbTzX3gmh2HSWgDJ3w+dZYy5rzliHcnEeFRlTvBLRpNPnJpBOMZg6AiviMHo+5uUqeNLrOIsC3Y2yBT0pD1lBGuVKa0zglKvjsUZEbR5+NeFcFrPSaZsQkO/+ttv/gneqt9h49PTTaMqeET7J40Yyxgs6cvyWFjHEiJ5OAaPP0EJ2TaHgBcD9et8gwJz3sEJdCCxj5ssWIXTEQP5PmyPfLFGs9ePtXA7krr81yp5A6Fc5+qbEhly3Da4xndovAJEVUL2pPFI4m4Q680Y8taR3RWXLkXw2rOc0Q4x+pCb6pk2wv8MYrw//X0dhkQluaa2mYd3Zvqxx80I5QqP8N1jbqpJSntm8qUYWswv+Rwf6Jxfqk=}
